name: weather-partner # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A sleek and user-friendly weather application # 79 char long summary
description: |
  A sleek and user-friendly weather application. It gathers weather information from user-built weather stations and provides precise global weather data sourced from Open Meteo.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  weather-partner:
    command: weather_partner
    extensions: [gnome]
    plugs:
    - network

parts:
  weather-partner:
    # See 'snapcraft plugins'
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
